name: swipe
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_mobx: ^1.1.0
  mobx: ^1.1.1
  flutter:
    sdk: flutter
  flutter_login_facebook: ^0.4.2+3

  flavor: ^1.0.1
  get_it: ^4.0.2
  get: ^2.14.1
  community_material_icon: ^3.5.95
  feature_discovery: ^0.8.0
  permission_handler: ^5.0.1+1
  firebase_core: "0.5.3"
  firebase_ml_vision: ^0.10.0
  local_auth: ^0.6.3+4
  google_maps_flutter: ^1.2.0
  package_info: ^0.4.3+4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  google_fonts: ^0.3.5
  shared_preferences: ^0.5.6
  hive: ^1.4.4+1
  hive_generator: ^0.8.2
  intl: ^0.16.1
  http: ^0.12.2
  path_provider: ^1.6.8
  path: ^1.6.4
  sensitive_http:
    git:
      url: "https://github.com/slowlearner/http.git"
      ref: preserve-headers-case
  pin_code_fields: ^6.0.1
  overlay_screen: ^1.2.0+1
  font_awesome_flutter: ^8.10.1
  sliding_up_panel: ^1.0.2
  firebase_auth: ^0.18.4+1
  google_sign_in: ^4.5.6
  cloud_firestore: ^0.14.4
  qr_flutter: ^3.2.0
  syncfusion_flutter_barcodes: ^18.4.46
  qr_code_scanner: ^0.3.4
  flutter_svg: ^0.18.0
  camera: ^0.5.8+1
  image: ^2.0.1
  mask_text_input_formatter: ^1.2.1
  carousel_slider: ^3.0.0
  image_picker: ^0.6.7+22
  native_screenshot: ^0.0.5
  flutter_markdown: ^0.4.1
  url_launcher: ^5.0.1
  geolocator: ^6.0.1
  vibration: ^1.7.3

dev_dependencies:
  build_runner: ^1.8.1
  flutter_test:
    sdk: flutter
  mobx_codegen: ^1.0.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  assets:
    - assets/svg2/
    - assets/images/
    - assets/svg/services/
    - assets/svg/services/cash-in/
    - assets/svg/promos/
    - assets/svg/help/
    - assets/svg/voucher-pockets/
    - assets/svg/services/bills-payment/
    - assets/icons/swipe-logo.png
    - assets/icons/image-placeholder.png
    - assets/icons/services/cash-in/
    - assets/icons/services/bank-transfer.png
    - assets/icons/services/buy-load.png
    - assets/icons/services/cash-in.png
    - assets/icons/services/insurance.png
    - assets/icons/services/more.png
    - assets/icons/services/pay-bills.png
    - assets/icons/services/pay-qr.png
    - assets/icons/services/remittance.png
    - assets/icons/services/request-money.png
    - assets/icons/services/map.png
    - assets/icons/services/bills-payment/cable-internet.png
    - assets/icons/services/bills-payment/credit-card.png
    - assets/icons/services/bills-payment/electricity.png
    - assets/icons/services/bills-payment/favorites.png
    - assets/icons/services/bills-payment/food.png
    - assets/icons/services/bills-payment/government.png
    - assets/icons/services/bills-payment/healthcare.png
    - assets/icons/services/bills-payment/insurance.png
    - assets/icons/services/bills-payment/loans.png
    - assets/icons/services/bills-payment/others.png
    - assets/icons/services/bills-payment/real-estate.png
    - assets/icons/services/bills-payment/school.png
    - assets/icons/services/bills-payment/telecom.png
    - assets/icons/services/bills-payment/transportation.png
    - assets/icons/services/bills-payment/water-utility.png
    - assets/icons/services/pay-qr/generate-qr.png
    - assets/icons/services/pay-qr/scan-qr.png
    - assets/icons/services/pay-qr/upload-qr.png
    - assets/icons/instapay.png
    - assets/icons/pesonet.png
    - assets/icons/autosweep.jpg
    - assets/icons/biometrics/fingerprint.png
    - assets/icons/biometrics/faceid.png
    - assets/icons/links-accounts/bpi.png
    - assets/icons/links-accounts/unionbank.png
    - assets/icons/merchant-partners/food.png
    - assets/icons/merchant-partners/retail.png
    - assets/icons/merchant-partners/entertainment.png
    - assets/icons/merchant-partners/pharmacies.png
    - assets/icons/merchant-partners/transportation.png
    - assets/icons/merchant-partners/supermarket.png
    - assets/icons/merchant-partners/store.png
    - assets/icons/merchant-partners/gadgets.png
    - assets/icons/merchant-partners/services.png
    - assets/icons/voucher-pockets/voucher-pockets.png
    - assets/icons/promos/undrawer-wallet.png
    - assets/icons/promos/undrawer-savings.png
    - assets/icons/help/help-ticket.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
